# Generated by Django 4.1.6 on 2023-02-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default=0, max_length=200, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default=0, max_length=200, verbose_name='title'),
        ),
    ]
